# Generated by Django 5.2.4 on 2025-07-08 12:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Наименование привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=280, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "date_begin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Дата начала выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=280, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "is_pleasanthabit",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "is_publichabit",
                    models.BooleanField(
                        default=False, verbose_name="Привычка опубликована"
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Периодичность привычки"
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "habit_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время на привычку",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="my_habbits.myhabit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
